config/routes.rb
# frozen_string_literal: true

GitHub::Application.routes.draw do
  if Rails.env.test?
    ::TestRoutes = ActionDispatch::Routing::RouteSet.new unless defined?(::TestRoutes)
    mount TestRoutes, at: "/"
  end

  REPO_REGEX = /(?:\w|\.|\-)+/i unless defined?(REPO_REGEX)
  # Copied from User::LOGIN_REGEX, but modified slightly because:
  # "Regexp anchor characters are not allowed in routing requirements"
  #
  # This supports "_" for legacy superfans with logins that still contain "_".
  # It also supports old usernames with leading dashes like -andrew-
  USERID_REGEX = /-?[a-z0-9][a-z0-9\-\_]*/i unless defined?(USERID_REGEX)

  # This supports int or shaish Gist IDs
  GISTID_REGEX   = /\d+|[a-f0-9]{32}|[a-f0-9]{20}?/ unless defined?(GISTID_REGEX)

  GIT_OID_REGEX = /[a-f0-9]{40}/ unless defined?(GIT_OID_REGEX)

  BRANCH_REGEX = /[^\/]+(\/[^\/]+)?/ unless defined?(BRANCH_REGEX)

  APP_FILTER_REGEX = %r{(app/)?[^/]+}i unless defined?(APP_FILTER_REGEX)

  # Allow periods and dashes in package names, but also allow % for URL-encoded characters
  PACKAGE_DEPENDENCY_REGEX = /(?:([-:.%\w]+)|(@[-:.\/%\w]+))/i unless defined?(PACKAGE_DEPENDENCY_REGEX)

  WEBHOOK_GUID_REGEX = /\h{8}-\h{4}-\h{4}-\h{4}-\h{12}/ unless defined?(WEBHOOK_GUID_REGEX)
  WEBHOOK_REGEX = /\d+/ unless defined?(WEBHOOK_REGEX)

  # GitHub fully supports IPv4 and IPv6. Routes don't allow anchors, so we must
  # convert the existing regex to a string, remove the anchors, and then convert
  # it back to a regex.
  IP_REGEX = Regexp.union(
    Regexp.new(Resolv::IPv4::Regex.to_s.gsub(/(\\A)|(\\z)/, "")),
    Regexp.new(Resolv::IPv6::Regex.to_s.gsub(/(\\A)|(\\z)/, "")),
  ) unless defined?(IP_REGEX)

  AUTHORIZATION_KEY_REGEX = /[a-f0-9]{20}|Iv1\.[a-f0-9]{16}/ unless defined?(AUTHORIZATION_KEY_REGEX)

  # Workspace names are built off the owner's login and the repository name. The
  # repo regex is inclusive of the user regex, so we can just use that.
  WORKSPACE_REGEX = REPO_REGEX unless defined?(WORKSPACE_REGEX)
  CODESPACE_REGEX = WORKSPACE_REGEX unless defined?(CODESPACE_REGEX)

  # This constraint will redirect all notifications routes to the relevant notifications v2 routes
  # unless the GitHub.notifications_v2_disabled? configuration is true.
  NOTIFICATIONS_V2_REDIRECT_CONSTRAINT = lambda do |request|
    !GitHub.notifications_v2_disabled?
  end unless defined?(NOTIFICATIONS_V2_REDIRECT_CONSTRAINT)

  # Internal: handle optional segments in Rails 2 and 3 compatible way
  def optional(segment)
    "(#{segment})"
  end

  ##
  # Status
  get "/status", to: "site#status_lolrails"

  # User Hovercards
  # Deprecated route slated to be removed
  get "/hovercards", to: "hovercards/users#show_legacy"

  ##
  # Comment Edit History
  resources :user_content_edits, only: [:show, :destroy]
  get "/user_content_edits/show_edit_history/:comment_id", to: "user_content_edits#show_edit_history", as: :show_comment_edit_history
  post "/user_content_edits/dismiss_edit_history_onboarding/:content_id", to: "user_content_edits#dismiss_edit_history_onboarding", as: :dismiss_edit_history_onboarding

  # Live updates
  get "/socket-worker.js", to: "socket_worker#show"
  get "/_ws", to: "web_sockets#show", as: :web_socket

  ##############################################################################
  # NOTE: Only routes that should work on BOTH GitHub and Gist should appear
  # before this line
  ##############################################################################

  # Gists
  gist_routes = -> do
    get     "/",                  to: "gists/gists#new", as: :new_gist
    get     "/new",               to: "gists/gists#new"
    post    "/",                  to: "gists/gists#create", as: :gists
    get     "/detect_language",   to: "gists/gists#detect_language", as: :detect_gist_language

    # Public listing urls
    get     "/discover",          to: "gists/listings#discover", as: :discover_gists
    get     "/gists",             to: redirect("/discover")

    get     "/forked",            to: "gists/listings#forked", as: :forked_gists
    get     "/starred",           to: "gists/listings#starred", as: :starred_gists

    get     "/search",            to: "gists/searches#show", as: :gist_search
    get     "/search/quick",      to: "gists/searches#quick", as: :gist_quicksearch

    get     "/mine",              to: "gists/listings#mine", as: :my_gist_listings
    get     "/mine/forked",       to: "gists/listings#my_forked"
    get     "/mine/starred",      to: "gists/listings#my_starred"

    get "/join",    to: "gists/users#new", as: :gist_signup

    # UserDashboardPinsController (for gists only)
    post "/users/:user_id/dashboard-pin/:item_id", to: "user_dashboard_pins#create",
      as: :user_dashboard_gist_pin
    delete "/users/:user_id/dashboard-pin/:item_id", to: "user_dashboard_pins#destroy"

    # Notification routes for gists
    post "/notifications/beta/mark",        to: "notifications_v2#mark_as_read"
    post "/notifications/beta/unmark",      to: "notifications_v2#mark_as_unread"
    post "/notifications/beta/archive",     to: "notifications_v2#mark_as_archived"
    post "/notifications/beta/unarchive",   to: "notifications_v2#mark_as_unarchived"
    post "/notifications/beta/subscribe",   to: "notifications_v2#mark_as_subscribed"
    post "/notifications/beta/unsubscribe", to: "notifications_v2#mark_as_unsubscribed"
    post "/notifications/beta/star",        to: "notifications_v2#mark_as_starred"
    post "/notifications/beta/unstar",      to: "notifications_v2#mark_as_unstarred"

    constraints user_id: USERID_REGEX, gist_id: GISTID_REGEX, sha: GIT_OID_REGEX do
      # Return the default file in a gist via raw
      get "/:user_id/:gist_id/raw", to: "gists/gists#raw",
        format: false, as: :raw_user_gist

      get "/:user_id/:gist_id/raw/:sha", to: "gists/gists#raw", format: false

      # Default raw route for a gist file at a specific revision
      get "/:user_id/:gist_id/raw/:sha/:file", to: "gists/gists#raw",
        format: false, constraints: { file: /.+/ },
        as: :raw_user_gist_sha_file

      get "/:user_id/:gist_id/raw/:file", to: "gists/gists#raw",
        format: false, constraints: { file: /.+/ }

      if GitHub.gist3_domain?
        get "/auth/github", to: "gists/sessions#new", as: :gist_oauth_login
        get "/auth/github/callback", to: "gists/sessions#create", as: :gist_oauth_callback
        post "/auth/github/logout", to: "gists/sessions#destroy", as: :gist_oauth_logout

        # Redirect support/contact links per #44072
        get "/support", to: redirect("/support", host: GitHub.host_name)
        get "/contact", to: redirect("/contact", host: GitHub.host_name), as: false
        get "/contact/:flavor", to: redirect("/contact/%{flavor}", host: GitHub.host_name), as: false
        get "/login",   to: redirect("/login",   host: GitHub.host_name), as: false

        post "/preview", to: "comment_preview#show", as: false

        # For comment image uploads
        post "/upload/policies/:model", to: "upload_policies#create"
        put  "/upload/:model(/:id)",    to: "uploads#update"
        post "/upload/:model(/:id)",    to: "uploads#create"

        # Allow switching between desktop and mobile experience
        post   "/site/mobile_preference", to: "site#mobile_preference"
        post   "/site/toggle_site_admin_and_employee_status", to: "site#toggle_site_admin_and_employee_status"
        post   "/site/toggle_site_admin_performance_stats",   to: "site#toggle_site_admin_performance_stats"

        # Allow setting user protocol for cloning
        post   "/users/set_protocol",  to: "users#set_protocol"

        # Shortcuts cheatsheet
        get    "/site/keyboard_shortcuts", to: "site#keyboard_shortcuts"

        # Redirect any stafftools request to GitHub host
        get "/stafftools/graphs/flamegraph", to: "stafftools/graphs#flamegraph"
        get "/stafftools(/:path)", to: redirect("/stafftools/%{path}", host: GitHub.host_name),
          constraints: { path: /.*/ }

        # Add routes for user statuses so they can be viewed and changed
        get "/users/status",           to: "user_statuses#show"
        put "/users/status",           to: "user_statuses#update"
        get "/users/status/members",   to: "user_statuses#member_statuses"
        get "/users/status/emoji",     to: "user_statuses#emoji_picker"
        get "/users/status/organizations", to: "user_statuses#org_picker"

        # Duplicate the notice dismissal path so notices can be dismissed on gist pages
        post "/settings/dismiss-notice/:notice", to: "settings/dismissals#create"

        get "/_render_node/:id/*path", to: "nodes#show"
      end

      # This route also handles the legacy routes of:
      # - /:gist_id
      # - /:gist_id.{txt,js,pibb}
      get     "/:user_id",          to: "gists/users#show", as: :user_gists
      get     "/:user_id/public",   to: "gists/users#show",
        as: :user_public_gists, visibility: "public"
      get     "/:user_id/secret",   to: "gists/users#show",
        as: :user_secret_gists, visibility: "secret"

      # - Handle: /:gist_id/:sha legacy route
      get     "/:user_id/:sha",     to: "gists/users#show"
      # - Handle: /:gist_id/:sha legacy route
      get     "/:user_id/:sha.txt", to: "gists/users#show"

      # - Handles /:gist_id/{forks,stars,revisions}
      get     "/:user_id/forks",   to: "gists/users#show", legacy_redirect: "forks"
      get     "/:user_id/stars",   to: "gists/users#show", legacy_redirect: "stars"
      get     "/:user_id/revisions",   to: "gists/users#show", legacy_redirect: "revisions"
      get     "/:user_id/download",   to: "gists/users#show", legacy_redirect: "download"

      get     "/:user_id/forked",   to: "gists/users#forked", as: :user_forked_gists
      get     "/:user_id/forked/public",   to: "gists/users#forked", visibility: "public"
      get     "/:user_id/forked/secret",   to: "gists/users#forked", visibility: "secret"

app/models/archived/gist.rb
# rubocop:disable Style/FrozenStringLiteralComment

class Archived::Gist < ApplicationRecord::Domain::Gists
  include Archived::Base
  include ::Gist::Backup
  include ::Gist::LegalHold

  ANONYMOUS_USERNAME = "anonymous"

  belongs_to :user

  # Archive records associations. These must be defined in order for the
  # archive/restore operations to cascade to other record types. Just add new
  # associations following the conventions below.
  has_many :gist_comments,        class_name: "Archived::GistComment",       dependent: :delete_all

  def to_param
    repo_name
  end

  # Public: Finds a gist given an name with owner
  #
  # owner     - The String login of the gist owner
  #             OR the full NWO string if repo_name is omitted.
  # repo_name - (optional) The String repo name for the Gist.
  #
  # Returns a Gist or nil if not found
  def self.with_name_with_owner(owner, repo_name = nil)
    owner, repo_name = owner.to_s.split("/") if repo_name.nil?
    return nil unless owner.present? && repo_name.present?

    if owner == ANONYMOUS_USERNAME
      where("user_id IS NULL AND repo_name = ?", repo_name).first
    else
      where(repo_name: repo_name, user_id: User.where(login: owner).pluck(:id)).first
    end
  end

  def user_param
    user ? user.login : ANONYMOUS_USERNAME
  end

  def name_with_owner(separator = "/")
    [user_param, repo_name].join(separator)
  end

  def visibility
    self["public"] ? "public" : "secret"
  end

  def anonymous?
    user_id.nil?
  end

  # Hard-code what we had as host attribute in case anything depends on this
  # existing.
  def route
    "dgit."
  end

  def shard_path
    GitHub::Routing.gist_storage_path(repo_name: repo_name)
  end

  # Limited use GitRPC::Client object for interacting with the git repository.
  # This should be used for creating / deleting the repository only.
  def rpc
    return @rpc if @rpc
    @rpc = GitRPC.new("chimney-transitional://#{host}#{shard_path}")
  end

  # Check if the repository directly exists on disk on the storage server. This
  # always makes an RPC call and should be used sparingly. Just because a
  # repository exists does not necessarily mean it has any branches, tags, or
  # other objects. The #empty? method is often a much better check for whether a
  # repository is in a useful state.
  #
  # If the repository isn't routed, returns false since there's no repo to check.
  #
  # Returns true when the repository exists.
  def exists_on_disk?
    host && shard_path && rpc.exist?
  end

  # For stafftools compatibility?
  def active?
    false
  end

  # Error thrown when we fail to delete a repository from the backups
  class DeleteError < StandardError
    attr_reader :data

    def initialize(data)
      @data = data
    end
  end

  def repository_spec
    "gist/#{repo_name}"
  end

  # Find archived records that are "purgeable" based on the age of the
  # updated_at attribute. Those repositories whose owner has a legal hold on
  # them are not candidates for pruning.
  #
  # limit - Maximum number of records to return.
  # age   - Time when records should be considered stale.
  #
  # Returns an Array of purgeable Archived::Gist objects.
  def self.find_stale_records(limit, age)
    ActiveRecord::Base.connected_to(role: :reading_slow) do
      stale_records = where("archived_gists.updated_at < ?", age).
        order("archived_gists.updated_at ASC").
        limit(limit).to_a

      return stale_records if stale_records.empty?

      user_ids_with_legal_hold = LegalHold.distinct.pluck(:user_id)
      stale_records.reject do |record|
        user_ids_with_legal_hold.include?(record.user_id)
      end
    end
  end

  # Purge archived records that are stale. By default this destroys the 10
  # oldest archived record that are more than 1 month old. Destroying the
  # records also removes git repositories from archive storage.
  #
  # limit - Maximum number of records to return.
  # age   - Time when records should be considered stale.
  #
  # Returns nothing.
  def self.purge_stale_records(limit = 10, age = 1.month.ago)
    records = find_stale_records(limit, age)
    records.each do |record|
      begin
        throttle do
          record.purge
        end
      rescue GitBackups::DeleteError => e
        # Errors are expected to happen and expected to be transient. We'll try to
        # delete this one the next time the job runs and we want to keep making
        # progress on the rest of the list
        GitHub::Logger.log({fn: "Archived::Gist.purge_stale_records",
                            spec: record.repository_spec,
                            message: e.message})
        next
      end
    end
  end

  def purge
    delete_backup
    destroy
  end

end

app/models/gist/backup.rb
# frozen_string_literal: true

module Gist::Backup
  include GitBackups

  def backups_enabled?
    GitHub.realtime_backups_enabled?
  end

  # Perform a backup via gitbackups
  def backup_ng!
    _run_backup_ng(false)
  end

  # Queue a job to run git-backup on the repository
  def async_backup(backfill = false)
    return unless backups_enabled?
    return if backfill # this comes from the legacy sweeper

    RepositoryBackupNgJob.perform_later(id, :gist)
  end
end

app/models/gist/importer.rb
# rubocop:disable Style/FrozenStringLiteralComment

require "open-uri"

# Used to import production Gists to development for testing.
#
# Usage:
#   Gist::Importer.import "ed298310dd7a92f10ff0", the("defunkt")
#
# Note: If you don't supply the user, it will create one based
#       off the user in the Gist data.
class Gist::Importer

  # Import Gist from production.
  #
  # gist_id - The id of the Gist.
  # user    - The user to assign to this Gist.
  #
  # Returns a Gist.
  def self.import(gist_id, user = nil)
    create_gist Octokit.gist(gist_id), user
  end

  # Private: Create a Gist from an API response
  #
  # data - The gist Hash of attributes from API
  # user    - The user to assign to this Gist.
  #
  # Returns a new Gist object imported from production.
  def self.create_gist(data, user)
    if gist = Gist.find_by_repo_name(data["id"])
      gist.remove(async: false)
    end

    user ||= if user_data = data["user"]
      User.find_by_login(user_data["login"])
    end

    gist_creator = Gist::Creator.new \
      repo_name: data["id"],
      user: user,
      public: data["public"],
      description: data["description"],
      contents: file_params_to_contents(data["files"]),
      created_at: data["created_at"],
      updated_at: data["updated_at"]

    if gist_creator.create
      Octokit.gist_comments(data["id"]).each do |comment|
        import_gist_comment(gist_creator.gist, comment, user)
      end
    else
      raise gist_creator.gist.errors.inspect
    end

    gist_creator.gist
  end

  def self.import_gist_comment(gist, comment, user)
    new_comment = gist.comments.new
    new_comment.created_at = comment["created_at"]
    new_comment.updated_at = comment["updated_at"]
    new_comment.body = comment["body"]
    new_comment.user = user
    new_comment.save!
  end

  # Private: Convert the file params to a contents hash
  #
  # files - The files hash from the API
  #
  # Returns a Hash of { "file_name" => "contents" }
  def self.file_params_to_contents(files)
    contents = []
    files.to_hash.each do |name, file_info|
      contents << { name: name.to_s, value: file_info["content"] }
    end
    contents
  end
end

app/models/gist/legal_hold.rb
# frozen_string_literal: true

module Gist::LegalHold
  # Does this gist have a legal hold placed on that should prevent it from
  # being removed entirely?
  #
  # Returns boolean.
  def legal_hold?
    # It's always possible that our owner has been wiped out. Just in case that
    # hold still managed to exist we'll provide an extra-safe method of
    # checking.
    ::LegalHold.find_by(user_id: user_id).present?
  end
end

app/views/gists/users/_navigation.html.erb
<nav class="reponav js-repo-nav" aria-label="Gist tab">
  <%= selected_link_to user_gists_path(view.user),
          :highlight => view.highlights_for_all,
          :class => "reponav-item",
          :"aria-label" => "All gists" do %>
    <%= octicon("gist") %>
    All gists
    <%= render Primer::CounterComponent.new(count: view.all_count) %>
  <% end %>

  <% if view.show_forked_tab? %>
    <%= selected_link_to user_forked_gists_path(view.user),
            :highlight => view.highlights_for_forked,
            :class => "reponav-item",
            :"aria-label" => "Forked" do %>
      <%= octicon("git-branch") %>
      Forked
      <%= render Primer::CounterComponent.new(count: view.forked_count) %>
    <% end %>
  <% end %>

  <% if view.show_starred_tab? %>
    <%= selected_link_to user_starred_gists_path(view.user),
            :highlight => view.highlights_for_starred,
            :class => "reponav-item",
            :"aria-label" => "Starred" do %>
      <%= octicon("star") %>
      Starred
      <%= render Primer::CounterComponent.new(count: view.starred_count) %>
    <% end %>
  <% end %>
</nav>

app/views/gists/users/_profile.html.erb
<%graphql
  fragment User on User {
    id
    isBlockedByViewer
    ...Views::Users::Profile::UserFragment
  }
%>
<%
  user = Views::Gists::Users::Profile::User.new(user)

  page_info dashboard_pinnable_item_id: user.id
%>

<div class="h-card col-3" itemscope itemtype="http://schema.org/Person">
  <% unless this_user.hide_from_user?(current_user) %>
    <%= render partial: "users/profile", locals: { user: user, blocking: logged_in? && user.is_blocked_by_viewer?, gists_profile: true } %>
  <% end %>

  <a class="btn btn-outline width-full text-center mt-3" href="<%= "#{GitHub.url}/#{this_user.to_param}" %>">
    View GitHub Profile
  </a>
</div>

app/views/gists/users/show.html.erb
<%# view is an instance of GistUsers::ShowPageView %>
<%graphql
  fragment Actor on Actor {
    login
    ... on User {
      ...Views::Gists::Users::Profile::User
    }
  }
%>

<%
  page_info \
    title: view.page_title,
    description: h(view.page_meta_description),
    stafftools: stafftools_user_gists_path(view.user),
    selected_link: view.current_page,
    responsive: responsive_gists_enabled?,
    richweb: {
      title: view.page_title,
      description: h(view.page_meta_description),
      type: "profile",
    }

  actor = Views::Gists::Users::Show::Actor.new(actor)
  is_user = actor.is_a?(PlatformTypes::User)

  content_for :head do
    discover_feed :atom, view.atom_feed_path
  end
%>

<%= render "gists/banner" %>

<% if view.show_spammy_alert? %>
  <div class="flash flash-error site-admin-alert container-lg px-3 mt-2">
    This user is flagged <strong>spammy</strong>
  </div>
<% end %>

<div class="container-lg px-3 new-discussion-timeline mt-4">
  <div class="gutter d-flex">
    <% if is_user %>
      <%= render "gists/users/profile", view: view, user: actor %>
    <% end %>

    <div class="<%= "col-9" if is_user %>">
      <div class="pagehead py-0">
        <div class="mb-4">
          <ul class="pagehead-actions">
            <% if view.show_filters? %>
              <li>
                <%= render "gists/gists/filter_options", view: view %>
              </li>
            <% end %>
            <li>
              <%= render "gists/gists/sort_options", view: view if view.has_gists? %>
            </li>
          </ul>
        </div>

        <%= render_partial_view "gists/users/navigation", view %>
      </div>



      <% if view.has_gists? %>
        <% view.gists_with_first_blob.each do |gist, blob| %>
          <%= render_partial_view "gists/gists/snippet", Gists::SnippetView, :gist => gist, :blob => blob %>
        <% end %>
        <div class="paginate-container">
          <%= simple_paginate(view.gists, :next_label => view.next_label, :previous_label => view.previous_label)%>
        </div>
      <% else %>
        <% if view.your_profile? %>
          <div class="blankslate">
            <h3>You don’t have any <%= view.scope_name %> yet.</h3>
            <% if view.all_gists? %>
              <p>Your public gists will show up here on your profile. <%= link_to "Create a gist", new_gist_path %> to get started.</p>
            <% end %>
          </div>
        <% else %>
          <div class="blankslate">
            <h3><%= actor.login %> doesn’t have any <%= view.scope_name %> yet.</h3>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>