config/routes.rb
    # WikiController
    post   "wiki/_preview",                     to: "wiki#preview",                          id: /[^\/]+/, version_list: /.*/
    get    "wiki",                              to: "wiki#index",        as: :wikis
    post   "wiki",                              to: "wiki#create",       as: nil
    put    "wiki/:id",                          to: "wiki#update",                           id: /[^\/]+/
    delete "wiki/:id",                          to: "wiki#destroy",                          id: /[^\/]+/
    post   "wiki/:id/_compare(/:version_list)", to: "wiki#compare",                          id: /[^\/]+/, version_list: /.*/
    get    "wiki/:id/_compare(/:version_list)", to: "wiki#compare",                          id: /[^\/]+/, version_list: /.*/
    get    "wiki/_history",                     to: "wiki#history"
    post   "wiki/_compare(/:version_list)",     to: "wiki#compare",                                                version_list: /.*/
    get    "wiki/_compare(/:version_list)",     to: "wiki#compare",                                                version_list: /.*/
    get    "wiki/_pages",                       to: "wiki#pages",        as: :wiki_pages
    get    "wiki/_new",                         to: "wiki#new",          as: :new_wiki
    post   "wiki/_revert/:older/:newer",        to: "wiki#revert"
    get    "wiki/:id/_edit",                    to: "wiki#edit",         as: :edit_wiki,  id: /[^\/]+/
    get    "wiki/:id/_current",                 to: "wiki#current",      as: :wiki_current, id: /[^\/]+/
    get    "wiki/:id/_history",                 to: "wiki#history",                          id: /[^\/]+/
    post   "wiki/:id/_revert/:older/:newer",    to: "wiki#revert",                           id: /[^\/]+/
    get    "wiki/:id",                          to: "wiki#show",         as: :wiki,       id: /[^\/]+/, defaults: { format: "html" }
    get    "wiki/:id/:version(/*path)",         to: "wiki#show",                             id: /[^\/]+/, format: false
    get    "wiki/*path",                        to: "wiki#show",                                              format: false
    get    "wikis(/*args)",                     to: "wiki#redirect"

    ##
    # Repositories
    match  "archives/*name",        to: "site#archive_redirect", as: :archives,       via: [:get, :post]
    match  "zipball/:name",         to: "tree#zipball",          as: :zipball_legacy, via: [:get, :post], name: /.+/
    match  "tarball/:name",         to: "tree#tarball",          as: :tarball_legacy, via: [:get, :post], name: /.+/
    match  "archive/*name.tar.gz",  to: "tree#archive",          as: :tarball,        via: [:get, :post], name: /.+/, format: false, _format: "tar.gz"
    match  "archive/*name.zip",     to: "tree#archive",          as: :zipball,        via: [:get, :post], name: /.+/, format: false, _format: "zip"

    get    "check",                     to: "tree#check",                    as: :check_repo
    post   "dismiss-tree-finder-help",  to: "tree#dismiss_tree_finder_help", as: :dismiss_list_help
    match  "find/:name",                to: "tree#find",                     as: :tree_find,    name: /.+/,  via: [:get, :post]
    match  "tree-list/:name",           to: "tree#list",                     as: :tree_list,    name: /.+/,  via: [:get, :post]

    # Aleph code navigation routes
    get    "find-symbols",              to: "code_nav#definition",        as: :code_nav_symbols
    get    "find-definition",           to: "code_nav#definition",        as: :code_nav_definition
    get    "find-references",           to: "code_nav#references",        as: :code_nav_references

    get "tree/delete/*name(/*path)", to: "tree#delete", as: :delete_directory, name: /(.|\n)+/, format: false, defaults: { format: :html }
    delete "tree/*name(/*path)", to: "tree#destroy", as: :destroy_directory, name: /(.|\n)+/, format: false, defaults: { format: :html }

    # nb: this endpoint is for backwards compability while migrating to refs#index instead
    get    "ref-list/*name(/*path)",      to: "refs#index",          as: :ref_list,           name: /.+/,                          format: false, defaults: { format: :html }
    get    "refs/*name(/*path)",          to: "refs#index",          as: :refs,               name: /.+/,                          format: false, defaults: { format: :html }
    get    "refs-tags/*name(/*path)",     to: "refs#tags",           as: :refs_tags,          name: /.+/,                          format: false, defaults: { format: :html }

    get    "tree/*name(/*path)",          to: "files#disambiguate",  as: :tree,               name: /.+/,                          format: false, defaults: { format: :html }
    get    "tree-commit/:name(/*path)",   to: "tree#tree_commit",    as: :tree_commit,        name: /.+/,                          format: false, defaults: { format: :html }
    get    "file-list/:name(/*path)",     to: "files#file_list",     as: :file_list,          name: /.+/,                          format: false, defaults: { format: :html }
    match  "blame/*name(/*path)",         to: "blob#blame",          as: :blame,              name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "tree-save/*name(/*path)",     to: "blob#save",           as: :file_save,          name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "new/*name(/*path)",           to: "blob#new",            as: :new_file,           name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "create/*name(/*path)",        to: "blob#create",         as: :create_file,        name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "edit/*name(/*path)",          to: "blob#edit",           as: :file_edit,          name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "delete/*name(/*path)",        to: "blob#delete",         as: :delete_file,        name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    delete "blob/*name(/*path)",          to: "blob#destroy",        as: :destroy_file,       name: /(.|\n)+/,                          format: false, defaults: { format: :html }
    match  "file-edit/:name(/*path)",     to: "blob#edit",                                    name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "preview/*name(/*path)",       to: "blob#preview",        as: :preview_edit,       name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    match  "raw/*name(/*path)",           to: "blob#raw",            as: :raw_blob,           name: /(.|\n)+/,  via: [:get, :post],  format: false, defaults: { format: :html }
    get    "blob/*name(/*path)",          to: "blob#show",           as: :blob,               name: /(.|\n)+/,                     format: false, defaults: { format: :html }
    get    "codeowners/*name(/*path)",    to: "blob#codeowners",     as: :codeowners,         name: /(.|\n)+/,                     format: false, defaults: { format: :html }

    get "contributors/*name(/*path)", to: "blob#contributors", as: :blob_contributors, name: /(.|\n)+/, format: false, defaults: { format: :html }
    get "contributors-list/*name(/*path)", to: "blob#contributors_list", as: :blob_contributors_list, name: /(.|\n)+/, format: false, defaults: { format: :html }

    match  "blob_excerpt/:oid",           to: "blob#excerpt",        as: :blob_excerpt,       oid: /[0-9a-f]{40}/, via: [:get, :post]

    # Noodle
    get  "workspace(/*name(/*path))",       to: "noodle#workspace",    as: :noodle_workspace,          name: /.+/,  format: false

    get    "files/:id(/*path)",   to: "repository_files#show", as: :repository_file, format: false

    get    "hovercard",           to: "hovercards/repositories#show",      as: :repository_hovercard
    post   "star",                to: "tree#star",                         as: :star_repository,        via: [:get, :post]
    post   "unstar",              to: "tree#unstar",                       as: :unstar_repository,      via: [:get, :post]
    match  "watchers",            to: "repositories#watchers",             as: :watchers,               via: [:get, :post]
    match  "stargazers",          to: "repositories#stargazers",           as: :stargazers_repository,  via: [:get, :post]
    match  "stargazers/you_know", to: "repositories#stargazers_you_know",  as: :stargazers_you_know,    via: [:get, :post]
    match  "contributors",        to: "repositories#contributors",         as: :contributors,           via: [:get, :post]
    match  "contributors_list",   to: "repositories#contributors_list",    as: :contributors_list,      via: [:get, :post]
    match  "used_by_list",        to: "repositories#used_by_list",         as: :used_by_list,           via: [:get, :post]
    match  "sponsors_list",       to: "repositories#sponsors_list",        as: :sponsors_list,          via: [:get, :post]
    match  "environment_status",  to: "repositories#environment_status",   as: :environment_status,     via: [:get, :post]
    match  "packages_list",       to: "repositories#packages_list",        as: :packages_list,          via: [:get, :post]
    match  "show_partial",        to: "tree#show_partial",                 as: :show_partial_tree,      via: [:get, :post]
    match  "noooooope",           to: "repositories#no_content",           as: :no_content,             via: [:get, :post]
    if GitHub.enterprise?
      get    "(/*gopkgpath)", to: "repositories#go_metatag", as: :go_tag, constraints: { query_string: "go-get=1" }
    end

    ##
    # Community contributors
    get    "community_contributors",           to: "repositories#community_contributors",          as: :community_contributors

app/views/navigation/_application_settings.html.erb
<%= render Primer::SubheadComponent.new(hide_border: true) do |component| %>
  <% component.slot(:heading, tag: :h2) do %>Applications<% end %>
<% end %>

<div class="tabnav">
  <nav class="tabnav-tabs" aria-label="Application settings">
    <%= selected_link_to "Installed GitHub Apps", gh_settings_installations_path(current_user), :class => "tabnav-tab", :highlight => [:integration_installations]%>
    <%= selected_link_to "Authorized GitHub Apps", settings_user_app_authorizations_path, :class => "tabnav-tab", :highlight => [:integrations_settings, :settings_user_authorized_integrations] %>
    <%= selected_link_to "Authorized OAuth Apps", settings_user_applications_path, :class => "tabnav-tab", :highlight => [:settings_user_authorized_apps] %>
  </nav>
</div>

app/views/navigation/_developer_settings.html.erb
<div class="col-3 float-left pr-4">
  <nav class="menu" aria-label="Developer settings" data-pjax>
    <%= selected_link_to "GitHub Apps", gh_settings_apps_path(current_user), :highlight => [:apps], :class => "menu-item" %>
    <%= selected_link_to "OAuth Apps", settings_user_developer_applications_path, :class => "menu-item", :highlight => [:settings_user_developer_applications] %>
    <%= selected_link_to "Personal access tokens", settings_user_tokens_path, :class => "menu-item", :highlight => :oauth_tokens %>
  </nav>
</div>

app/views/navigation/_devtools.html.erb
<%# erblint:disable LandmarkHasLabel %>
<nav class="reponav" role="navigation">
  <%= selected_link_to surveys_path,
          :highlight => :surveys,
          :class => "reponav-item" do %>
    <%= octicon('checklist') %>
    Surveys
  <% end %>

  <% if GitHub.spamminess_check_enabled? %>
    <%= selected_link_to devtools_spamurai_path,
            :highlight => :spamurai,
            :class => "reponav-item" do %>
      <%= octicon('flame') %>
      Spamuari
    <% end %>
  <% end %>

  <%= selected_link_to backscatter_path,
          :highlight => :backscatter,
          :class => "reponav-item" do %>
    <%= octicon('telescope') %>
    Backscatter
  <% end %>

  <%= selected_link_to code_experiments_path,
          :highlight => :code_experiments,
          :class => "reponav-item" do %>
    <%= octicon('beaker') %>
    Code experiments
  <% end %>

  <%= selected_link_to newsletters_path,
          :highlight => :newsletters,
          :class => "reponav-item" do %>
    <%= octicon('mail') %>
    Newsletters
  <% end %>

  <%= selected_link_to devtools_jobs_path,
          :highlight => :background_jobs,
          :class => "reponav-item" do %>
    <%= octicon('terminal') %>
    Background jobs
  <% end %>

  <%= selected_link_to devtools_feature_flags_path,
          :highlight => :features,
          :class => "reponav-item" do %>
    <%= octicon('squirrel') %>
    Features
  <% end %>
</nav>

app/views/navigation/_edit_repository.html.erb
<% collaboration_label = "Collaborators" %>
<% show_interaction_limit_nav = GitHub.interaction_limits_enabled? && !current_repository.private? %>
<% show_tiered_reporting_nav = current_repository.can_access_tiered_reporting?(current_user) %>

<div data-pjax>
  <nav class="menu" aria-label="Repository settings">
    <%= selected_link_to "Options", edit_repository_path(current_repository), :class => "menu-item" %>

    <% if GitHub.flipper[:repo_access_management].enabled?(current_repository.owner) || GitHub.flipper[:repo_access_management].enabled?(current_user) %>
      <%= selected_link_to "Manage access", repository_access_management_path, class: "menu-item", :highlight => :role_details %>
    <% else %>
      <% repo_collab_label = current_repository.in_organization? ? "Collaborators & teams" : "Collaborators" %>
      <%= selected_link_to repo_collab_label, repository_access_management_path, class: "menu-item" %>
    <% end %>

    <% unless GitHub.enterprise? %>
      <%= selected_link_to "Security & analysis", repository_security_and_analysis_path, class: "menu-item" %>
    <% end %>

    <% if current_repository.heads.any? %>
      <%= selected_link_to "Branches", edit_repository_branches_path, :class => "menu-item", :highlight => :repo_branch_settings %>
    <% end %>

    <%= selected_link_to "#{GitHub.enterprise? ? 'Hooks' : 'Webhooks'}", hooks_path(current_repository), :highlight => :hooks, :class => "menu-item" %>
    <%= selected_link_to "Notifications", repository_notification_settings_path(current_repository.owner, current_repository), :highlight => :notifications, :class => "menu-item" %>
    <%= selected_link_to "Integrations", repository_installations_path(current_repository.owner, current_repository), :highlight => :integration_installations, :class => "menu-item" %>

    <%= selected_link_to "Deploy keys", repository_keys_path, :class => "menu-item", :highlight => :repo_keys_settings %>

    <% if GitHub.custom_tabs_enabled? %>
      <%= selected_link_to "Custom tabs", repository_tabs_path, :class => "menu-item" %>
    <% end %>

    <% if current_repository.plan_supports?(:custom_key_links) %>
      <%= selected_link_to "Autolink references", key_links_path, :class => "menu-item", :highlight => :key_links_settings %>
    <% end %>

    <% if GitHub.actions_enabled? %>
      <%= selected_link_to "Secrets", repository_secrets_path, :class => "menu-item", highlight: :secrets_settings %>

      <%= selected_link_to "Actions", repository_actions_settings_path, :class => "menu-item", highlight: :repo_actions_settings %>
    <% end %>
  </nav>

  <% if current_repository.unsupported_pages? %>
    <nav aria-label="GitHub Pages settings" class="menu">
      <%= selected_link_to repository_page_path, :class => "menu-item text-red", :highlight => :unpublish_page_settings do %>
        Unpublish GitHub Pages <%= octicon("alert", class: "text-red ml-2") %>
      <% end %>
    </nav>
  <% end %>


  <% if show_interaction_limit_nav || show_tiered_reporting_nav %>
    <nav class="menu" aria-label="Repository moderation settings" data-pjax>
      <h3 class="menu-heading">
        Moderation
      </h3>
      <% if show_interaction_limit_nav %>
        <%= selected_link_to repository_interaction_limits_path(current_repository.owner, current_repository), highlight: :interaction_limits, class: "menu-item" do %>
          Interaction limits
          <% if RepositoryInteractionAbility.has_active_limits?(:repository, current_repository) %>
            <%= octicon "clock", class: "text-green" %>
          <% end %>
        <% end %>
      <% end %>

      <% if show_tiered_reporting_nav %>
        <%= selected_link_to reported_content_path(current_repository.owner, current_repository), highlight: :reported_content, class: "menu-item" do %>
          Reported content
        <% end %>
      <% end %>
    </nav>
  <% end %>
</div>

app/views/navigation/_fgp_edit_repository.html.erb
<%graphql
  fragment Repository on Repository {
    isArchived
    viewerCanToggleWiki
    viewerCanToggleProjects
    viewerCanSetInteractionLimits
    viewerCanManageWebhooks
    viewerCanManageDeployKeys
  }
%>
<% repository = Views::Navigation::FgpEditRepository::Repository.new(repository) %>

<%
  show_options =
    repository.viewer_can_toggle_wiki? ||
    repository.viewer_can_toggle_projects?

  show_webhooks = repository.viewer_can_manage_webhooks?

  show_deploy_keys = repository.viewer_can_manage_deploy_keys?

  show_interaction_limits = GitHub.interaction_limits_enabled? &&
    !current_repository.private? &&
    repository.viewer_can_set_interaction_limits?

  show_sidebar =
    !repository.is_archived? &&
    (show_options || show_interaction_limits || show_webhooks || show_deploy_keys)
%>

<% if show_sidebar %>
  <div class="col-3" data-pjax>
    <% if show_options || show_webhooks || show_deploy_keys %>
      <nav class="menu" aria-label="Repository settings">
        <% if show_options %>
          <%= selected_link_to "Options", edit_repository_path(current_repository), :class => "menu-item" %>
        <% end %>
        <% if show_webhooks %>
          <%= selected_link_to "#{GitHub.enterprise? ? 'Hooks' : 'Webhooks'}", hooks_path(current_repository), :highlight => :hooks, :class => "menu-item" %>
        <% end %>
        <% if show_deploy_keys %>
          <%= selected_link_to "Deploy keys", repository_keys_path, :class => "menu-item", :highlight => :repo_keys_settings %>
        <% end %>
      </nav>
    <% end %>

    <% if GitHub.interaction_limits_enabled? && !current_repository.private? %>
      <% if repository.viewer_can_set_interaction_limits? %>
        <nav class="menu" aria-label="Repository moderation settings" data-pjax>
          <h3 class="menu-heading">
            Moderation
          </h3>
          <%= selected_link_to repository_interaction_limits_path(current_repository.owner, current_repository), highlight: :interaction_limits, class: "menu-item" do %>
            Interaction limits
            <% if RepositoryInteractionAbility.has_active_limits?(:repository, current_repository) %>
              <%= octicon "clock", class: "text-green" %>
            <% end %>
          <% end %>
        </nav>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/navigation/_milestones.html.erb
<div class="subnav">
  <% if current_user_can_push? && current_repository_writable? %>
    <a href="<%= new_milestone_path(current_repository.owner, current_repository) %>" class="btn btn-primary float-right">New milestone</a>
  <% end %>
  <%= render :partial => "issues/navigation" %>
</div>

app/views/navigation/_oauth_application.html.erb
<div class="col-3 float-left pr-4">
  <nav class="menu" aria-label="OAuth App settings" data-pjax>
    <%= selected_link_to "General", oauth_application_path(current_application), :highlight => [:oauth_app], :class => "menu-item" %>
    <%= selected_link_to "Beta features", settings_oauth_application_beta_features_path(current_application), :highlight => [:oauth_app_beta], :class => "menu-item" %>
    <%= selected_link_to "Advanced", settings_oauth_application_advanced_path(current_application), :highlight => [:oauth_app_advanced], :class => "menu-item" %>
  </nav>
</div>

app/views/navigation/_security_workspace.html.erb
<% view = NavigationHelper::RepositoryNavigationView.new(current_user, repository) %>

<nav class="reponav js-repo-nav js-sidenav-container-pjax <% if container_xl? %>container-xl<% else %>container-lg<% end %> <%= responsive? ? "p-responsive d-none d-lg-block" : "px-3" %>"
     itemscope
     itemtype="http://schema.org/BreadcrumbList"
     aria-label="Temporary private fork"
     data-pjax="#js-repo-pjax-container">

  <span itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
    <%= selected_link_to(
          repository_path(repository, current_branch_or_tag_name),
          { :class => "reponav-item",
          :highlight => view.highlights_for_code,
          "data-hotkey" => "g c",
          "itemprop" => "url" }.merge(test_selector_data_hash("code-tab"))) do %>
      <%= octicon("code") %>
      <span itemprop="name">Code</span>
      <meta itemprop="position" content="1">
    <% end %>
  </span>

  <span itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
    <%= selected_link_to(
          pull_requests_path,
          { :class => "reponav-item",
          :highlight => view.highlights_for_pulls,
          "data-hotkey" => "g p",
          "itemprop" => "url" }.merge(test_selector_data_hash("pull-requests-tab"))) do %>
      <%= octicon("git-pull-request") %>
      <span itemprop="name">Pull requests</span>
      <%= render Primer::CounterComponent.new(count: view.open_pull_request_count, limit: 5_000) %>
      <meta itemprop="position" content="2">
    <% end %>
  </span>
</nav>

<% if responsive? %>
  <%= render partial: "navigation/security_workspace_small", locals: { repository: repository, view: view } %>
<% end %>

app/views/navigation/_security_workspace_small.html.erb
<div class="reponav-wrapper reponav-small d-lg-none">
  <nav class="reponav js-reponav text-center no-wrap"
       aria-label="Temporary private fork"
       itemscope
       itemtype="http://schema.org/BreadcrumbList">

    <span itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
      <%= selected_link_to(
            repository_path(repository, current_branch_or_tag_name),
            :class => "reponav-item",
            :highlight => view.highlights_for_code,
            "itemprop" => "url") do %>
        <span itemprop="name">Code</span>
        <meta itemprop="position" content="1">
      <% end %>
    </span>

    <span itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
      <%= selected_link_to(
            pull_requests_path,
            :class => "reponav-item",
            :highlight => view.highlights_for_pulls,
            "itemprop" => "url") do %>
        <span itemprop="name">Pull requests</span>
        <%= render Primer::CounterComponent.new(count: view.open_pull_request_count, limit: 5_000) %>
        <meta itemprop="position" content="2">
      <% end %>
    </span>
  </nav>
</div>

app/views/navigation/_settings.html.erb
<%# view is an instance of Settings::NavigationView %>

<div class="col-3 float-left pr-4">
  <nav class="menu position-relative" aria-label="Personal settings" data-pjax>
    <%= render partial: "navigation/settings_context_dropdown", locals: {
      title: "Personal settings",
      current_context: current_user
    } %>

    <%= selected_link_to "Profile", settings_user_profile_path, class: "menu-item", highlight: :avatar_settings %>
    <%= selected_link_to "Account", settings_user_admin_path, class: "menu-item" %>
    <%= selected_link_to security_and_privacy_section_title, settings_user_security_path, class: "menu-item" %>
    <%= selected_link_to "Security log", settings_user_audit_log_path, class: "menu-item", highlight: :audit_log %>
    
    <% unless GitHub.enterprise? %>
      <%= selected_link_to "Security & analysis", settings_user_security_analysis_path, class: "menu-item" %>
    <% end %>

    <%= selected_link_to settings_user_emails_path, class: "menu-item" do %>
      Emails
      <% if view.should_verify_email? %>
        <%= octicon("alert", class: "menu-warning", title: "You have not verified any email addresses") %>
      <% end %>
    <% end %>

    <%= selected_link_to "Notifications", settings_user_notifications_path, class: "menu-item" %>

    <% if view.should_show_scheduled_reminders? %>
      <%= selected_link_to "Scheduled reminders", personal_reminders_path, class: "menu-item", highlight: :reminders %>
    <% end %>

    <% if GitHub.billing_enabled? %>
      <%= selected_link_to "Billing", settings_user_billing_path, class: "menu-item", highlight: :user_billing_settings %>
    <% end %>

    <%= selected_link_to "SSH and GPG keys", settings_user_keys_path, class: "menu-item", highlight: :ssh_certificate_authorities %>

    <% if GitHub.user_abuse_mitigation_enabled? %>
      <%= selected_link_to "Blocked users", settings_user_blocks_path, class: "menu-item" %>
    <% end %>

    <%= selected_link_to "Repositories", settings_user_repositories_path, class: "menu-item", highlight: [:deleted_repositories] %>
    <%= selected_link_to "Organizations", settings_user_organizations_path, class: "menu-item" %>

    <% if view.enterprise_member? %>
      <%= selected_link_to "Enterprises", settings_user_enterprises_path, class: "menu-item" %>
    <% end %>

    <%= selected_link_to "Saved replies", saved_replies_path, class: "menu-item", highlight: :edit_saved_reply %>

    <%= selected_link_to "Applications", gh_settings_installations_path(current_user), class: "menu-item", highlight: [:applications_settings] %>

    <% if (GitHub::Connect.unified_contributions_enabled? || GitHub::Connect.unified_private_search_enabled?) && !GitHub.fedramp_private_instance? %>
      <%= selected_link_to "GitHub Connect", settings_dotcom_user_path, class: "menu-item", highlight: :dotcom_user %>
    <% end %>
  </nav>

  <nav class="menu" aria-label="Developer settings">
    <%= link_to gh_settings_apps_path(current_user), class: "menu-item" do %>
      Developer settings
    <% end %>
  </nav>
</div>

app/views/navigation/_settings_repositories.html.erb
<div class="table-list-filters d-flex">
  <div class="table-list-header-toggle states flex-justify-start pl-3">
    <%= selected_link_to octicon("repo") + " Repositories", settings_user_repositories_path, class: "btn-link" %>
    <%= selected_link_to octicon("trashcan") + " Deleted repositories", settings_user_deleted_repositories_path, class: "btn-link" %>
  </div>
</div>

app/views/navigation/_site_admin.html.erb
<%# erblint:disable LandmarkHasLabel %>
<%# erblint:counter TooltipCounter 7 %>
<%# rubocop:disable Lint/InstanceVariable %>

<div class="col-1 mt-3">
  <ul class="site-admin-menu-group" role="navigation">
    <li class="tooltipped tooltipped-w" aria-label="User info">
      <%= selected_link_to [:stafftools, @user],
              :highlight => :account_info,
              :class => "site-admin-menu-item" do %>
        <%= octicon('info') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="Billing">
      <%= selected_link_to [:billing, :admin, @user],
              :highlight => :billing,
              :class => "site-admin-menu-item" do %>
        <%= octicon('credit-card') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="Security">
      <%= selected_link_to [:security, :admin, @user],
              :highlight => :security,
              :class => "site-admin-menu-item" do %>
        <%= octicon('lock') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="Repositories">
      <%= selected_link_to [:repositories, :stafftools, @user],
              :highlight => :repositories,
              :class => "site-admin-menu-item" do %>
        <%= octicon('repo') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="Organizations">
      <%= selected_link_to [:stafftools, @user, :organization_memberships],
              :highlight => :organizations,
              :class => "site-admin-menu-item" do %>
        <%= octicon('organization') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="Collaboration">
      <%= selected_link_to [:collab_repos, :stafftools, @user],
              :highlight => :collaboration,
              :class => "site-admin-menu-item" do %>
        <%= octicon('comment') %>
      <% end %>
    </li>
    <li class="tooltipped tooltipped-w" aria-label="OAuth">
      <%= selected_link_to [:stafftools, @user, :applications],
              :highlight => :oauth,
              :class => "site-admin-menu-item" do %>
        <%= octicon('link') %>
      <% end %>
    </li>
  </ul>
</div>